"""
Investor Relations Agent for Epochal Capital.

Responsible for:
- Drafting long-form content (Substack, LinkedIn articles)
- Creating social media content (Twitter/X threads)
- Generating investor updates and LP communications
- Supporting fundraising with pitch materials
- Maintaining consistent brand voice and messaging
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional
from enum import Enum

from epochal.agents.base import Agent, AgentRole, AgentTask, AgentResult, TaskStatus
from epochal.core.portfolio import Portfolio
from epochal.core.thesis import InvestmentThesis


class ContentType(Enum):
    """Types of content the IR agent can generate."""
    SUBSTACK_ARTICLE = "substack_article"
    LINKEDIN_POST = "linkedin_post"
    TWITTER_THREAD = "twitter_thread"
    INVESTOR_UPDATE = "investor_update"
    LP_LETTER = "lp_letter"
    PITCH_DECK_NARRATIVE = "pitch_deck_narrative"
    PRESS_RELEASE = "press_release"
    MARKET_COMMENTARY = "market_commentary"


class ContentTone(Enum):
    """Tone for content generation."""
    PROFESSIONAL = "professional"
    THOUGHT_LEADERSHIP = "thought_leadership"
    EDUCATIONAL = "educational"
    EXCITING = "exciting"
    ANALYTICAL = "analytical"


@dataclass
class ContentDraft:
    """A content draft generated by the IR agent."""
    content_type: ContentType
    title: str
    body: str
    summary: Optional[str] = None
    hashtags: list[str] = field(default_factory=list)
    call_to_action: Optional[str] = None
    target_audience: str = "investors"
    tone: ContentTone = ContentTone.PROFESSIONAL
    created_at: datetime = field(default_factory=datetime.utcnow)
    word_count: int = 0

    def __post_init__(self):
        self.word_count = len(self.body.split())

    def to_dict(self) -> dict:
        return {
            "content_type": self.content_type.value,
            "title": self.title,
            "body": self.body,
            "summary": self.summary,
            "hashtags": self.hashtags,
            "call_to_action": self.call_to_action,
            "target_audience": self.target_audience,
            "tone": self.tone.value,
            "created_at": self.created_at.isoformat(),
            "word_count": self.word_count,
        }


class InvestorRelationsAgent(Agent):
    """
    Agent responsible for investor relations and content creation.

    Capabilities:
    - draft_substack: Long-form thought leadership articles
    - draft_linkedin: Professional network posts
    - draft_twitter: Twitter/X threads
    - draft_investor_update: Quarterly/monthly LP updates
    - draft_fundraising_pitch: Fundraising materials
    - generate_market_commentary: AI market analysis
    """

    # Brand voice guidelines
    BRAND_VOICE = {
        "name": "Epochal Capital",
        "tagline": "Investing at the AI Inflection Point",
        "positioning": "AI-focused investment fund targeting private companies with upcoming liquidity events",
        "key_themes": [
            "AI transformation of industries",
            "Liquidity-focused investing",
            "Data-driven deal sourcing",
            "Multi-agent operational excellence",
        ],
        "tone_guidelines": [
            "Authoritative but accessible",
            "Forward-looking and optimistic",
            "Data-driven and analytical",
            "Transparent about thesis and process",
        ],
    }

    def __init__(self, portfolio: Optional[Portfolio] = None):
        super().__init__(
            role=AgentRole.INVESTOR_RELATIONS,
            name="Investor Relations Agent",
            description="Manages investor communications, content creation, and fundraising support",
        )
        self.portfolio = portfolio or Portfolio()
        self.thesis = InvestmentThesis()

    def _register_capabilities(self):
        """Register IR capabilities."""
        self.register_capability(
            name="draft_substack",
            description="Draft long-form Substack article",
            handler=self._draft_substack,
            required_inputs=["topic"],
        )
        self.register_capability(
            name="draft_linkedin",
            description="Draft LinkedIn post",
            handler=self._draft_linkedin,
            required_inputs=["topic"],
        )
        self.register_capability(
            name="draft_twitter",
            description="Draft Twitter/X thread",
            handler=self._draft_twitter,
            required_inputs=["topic"],
        )
        self.register_capability(
            name="draft_investor_update",
            description="Draft investor/LP update",
            handler=self._draft_investor_update,
        )
        self.register_capability(
            name="draft_fundraising_pitch",
            description="Draft fundraising pitch narrative",
            handler=self._draft_fundraising_pitch,
        )
        self.register_capability(
            name="generate_market_commentary",
            description="Generate AI market commentary",
            handler=self._generate_market_commentary,
        )

    async def execute_task(self, task: AgentTask) -> AgentResult:
        """Execute an IR task."""
        start_time = datetime.utcnow()
        task.status = TaskStatus.IN_PROGRESS
        task.started_at = start_time

        try:
            capability_name = task.input_data.get("capability", "draft_linkedin")
            topic = task.input_data.get("topic", "AI Investment Landscape")

            if capability_name == "draft_substack":
                result_data = await self._draft_substack(topic)
            elif capability_name == "draft_linkedin":
                result_data = await self._draft_linkedin(topic)
            elif capability_name == "draft_twitter":
                result_data = await self._draft_twitter(topic)
            elif capability_name == "draft_investor_update":
                result_data = await self._draft_investor_update()
            elif capability_name == "draft_fundraising_pitch":
                result_data = await self._draft_fundraising_pitch()
            elif capability_name == "generate_market_commentary":
                result_data = await self._generate_market_commentary()
            else:
                raise ValueError(f"Unknown capability: {capability_name}")

            execution_time = (datetime.utcnow() - start_time).total_seconds()
            self.tasks_completed += 1

            return AgentResult(
                task_id=task.id,
                success=True,
                data=result_data,
                execution_time_seconds=execution_time,
            )

        except Exception as e:
            self.tasks_failed += 1
            return AgentResult(
                task_id=task.id,
                success=False,
                error=str(e),
                execution_time_seconds=(datetime.utcnow() - start_time).total_seconds(),
            )

    async def _draft_substack(self, topic: str) -> dict:
        """Draft a long-form Substack article."""
        # Get portfolio context
        summary = self.portfolio.get_portfolio_summary()

        article = ContentDraft(
            content_type=ContentType.SUBSTACK_ARTICLE,
            title=self._generate_article_title(topic),
            body=self._generate_substack_body(topic, summary),
            summary=f"Epochal Capital's perspective on {topic}",
            hashtags=["AI", "Investing", "VentureCapital", "TechInvesting"],
            call_to_action="Subscribe to stay updated on AI investment opportunities",
            target_audience="LPs, prospective investors, AI industry professionals",
            tone=ContentTone.THOUGHT_LEADERSHIP,
        )

        return {
            "draft": article.to_dict(),
            "platform": "Substack",
            "recommended_publish_time": "Tuesday or Thursday, 10am EST",
            "estimated_read_time": f"{article.word_count // 200} minutes",
        }

    def _generate_article_title(self, topic: str) -> str:
        """Generate an engaging article title."""
        titles = {
            "thesis": "Why We're Betting Big on AI Liquidity Events in 2026",
            "market": "The AI Investment Landscape: Where We See Opportunity",
            "process": "Inside Epochal Capital: How We Source AI Deals",
            "portfolio": "Our AI Portfolio: Thesis in Action",
            "agents": "Building an AI-Native Investment Firm",
            "infrastructure": "AI Infrastructure: The Picks and Shovels of the AI Revolution",
            "liquidity": "The Coming Wave of AI IPOs: Our Playbook",
        }
        # Match topic to title or generate default
        for key, title in titles.items():
            if key in topic.lower():
                return title
        return f"Epochal Capital on {topic}: An Investment Perspective"

    def _generate_substack_body(self, topic: str, summary) -> str:
        """Generate Substack article body."""
        return f"""
# {self._generate_article_title(topic)}

*By the Epochal Capital Team*

---

## The Opportunity

We're living through the most significant technological transformation since the internet. Artificial intelligence is not just changing how we work—it's redefining what's possible across every industry.

At Epochal Capital, we've positioned ourselves at the intersection of this transformation and a unique market opportunity: **private AI companies approaching liquidity events**.

## Our Thesis

Our investment thesis is built on three core convictions:

### 1. AI is Transformational, Not Incremental

The companies we're tracking aren't building features—they're building new categories. From foundation models to AI infrastructure to autonomous agents, we're seeing the emergence of platforms that will define the next decade of technology.

### 2. Liquidity Windows Are Opening

After years of private market growth, we're seeing clear signals that liquidity events are approaching. IPO filings, strategic M&A activity, and secondary market dynamics all point to a significant exit wave in 2026-2027.

### 3. Information Asymmetry Creates Alpha

The private AI market is opaque. Valuations, revenue metrics, and strategic developments often lag public knowledge by months. Our multi-agent research system helps us stay ahead of the market.

## What We're Seeing

Our current watchlist includes {summary.companies_tracked} companies across the AI ecosystem:

- **Foundation Models**: The core platforms powering the AI revolution
- **Infrastructure**: The compute, data, and tooling layers enabling AI at scale
- **Applications**: Vertical-specific AI implementations with clear paths to revenue

## Our Edge: Multi-Agent Operations

What makes Epochal Capital different isn't just our thesis—it's how we operate.

We've built a multi-agent system that automates key aspects of deal sourcing, due diligence, and portfolio monitoring. This allows us to:

- **Research at scale**: Comprehensive coverage of 20+ companies with twice-weekly refreshes
- **Score objectively**: Quantitative thesis scoring that removes emotional bias
- **Move quickly**: Real-time alerts on material developments

## Looking Ahead

The AI investment landscape is evolving rapidly. We see 2026 as a pivotal year for liquidity events, with several of our top-rated opportunities targeting IPOs.

For investors seeking exposure to this transformation, the window is narrowing. The best opportunities won't stay private forever.

---

*Epochal Capital is an AI-focused investment fund. This content is for informational purposes only and does not constitute investment advice.*

**Want to learn more? [Contact us](mailto:ir@epochal.capital) or subscribe for updates.**
"""

    async def _draft_linkedin(self, topic: str) -> dict:
        """Draft a LinkedIn post."""
        post = ContentDraft(
            content_type=ContentType.LINKEDIN_POST,
            title="",  # LinkedIn posts don't have separate titles
            body=self._generate_linkedin_body(topic),
            hashtags=["AI", "Investing", "VentureCapital", "PrivateEquity", "TechInvesting"],
            call_to_action="Follow Epochal Capital for more AI investment insights",
            target_audience="Finance professionals, tech executives, LPs",
            tone=ContentTone.PROFESSIONAL,
        )

        return {
            "draft": post.to_dict(),
            "platform": "LinkedIn",
            "recommended_publish_time": "Tuesday-Thursday, 8-10am local time",
            "character_count": len(post.body),
        }

    def _generate_linkedin_body(self, topic: str) -> str:
        """Generate LinkedIn post body."""
        return f"""🚀 The AI investment landscape is shifting.

At Epochal Capital, we're seeing clear signals that 2026 will be a landmark year for AI liquidity events.

Here's what we're tracking:

📊 **Foundation Models** — The race to build the most capable AI systems is intensifying. We're watching companies with differentiated moats and clear enterprise adoption.

🔧 **AI Infrastructure** — The "picks and shovels" of AI are generating real revenue. GPU clouds, inference optimization, and data infrastructure are seeing explosive demand.

🤖 **AI Agents** — The next frontier. Autonomous systems that can take actions, not just generate text. Early but high-potential.

Our thesis: Focus on private AI companies with upcoming liquidity events (IPO, M&A, secondary).

Why now?
• Valuations have rationalized from 2021 peaks
• Enterprise AI adoption is accelerating
• IPO pipelines are rebuilding

We've built a multi-agent system to source and evaluate opportunities at scale. Data-driven. Thesis-aligned. Execution-focused.

What trends are you seeing in AI investing? Drop your thoughts below 👇

#AI #Investing #VentureCapital #PrivateMarkets #ArtificialIntelligence #TechInvesting #FutureOfFinance
"""

    async def _draft_twitter(self, topic: str) -> dict:
        """Draft a Twitter/X thread."""
        thread = self._generate_twitter_thread(topic)

        return {
            "draft": {
                "content_type": ContentType.TWITTER_THREAD.value,
                "thread": thread,
                "tweet_count": len(thread),
                "total_characters": sum(len(t) for t in thread),
            },
            "platform": "Twitter/X",
            "recommended_publish_time": "Weekdays 12-1pm or 5-6pm EST",
            "hashtags": ["AI", "Investing", "VentureCapital"],
        }

    def _generate_twitter_thread(self, topic: str) -> list[str]:
        """Generate a Twitter thread."""
        return [
            "🧵 Thread: Why we think 2026 will be the year of AI IPOs\n\nAt @EpochalCapital, we're tracking 20+ private AI companies. Here's what we're seeing...",

            "1/ The AI market has matured significantly since the ChatGPT moment.\n\nCompanies now have:\n• Real revenue ($100M+ ARR common)\n• Enterprise customers\n• Clear competitive moats\n\nThese aren't science projects anymore.",

            "2/ IPO infrastructure is rebuilding.\n\nWe're seeing:\n• Banks staffing up AI coverage\n• Investor appetite returning\n• Several companies hiring IPO advisors\n\nThe pipeline is filling.",

            "3/ Our top-rated opportunities (by thesis score):\n\n🥇 Anthropic - 92.5/100\n🥈 Glean - 79.5/100  \n🥉 Mistral AI - 79.5/100\n\nStrong fundamentals + clear liquidity paths.",

            "4/ What makes a strong AI investment?\n\nOur scoring model weights:\n• Liquidity signals (25%)\n• Vertical fit (25%)\n• Investor quality (20%)\n• Stage fit (20%)\n• Revenue metrics (15%)",

            "5/ Red flags we watch for:\n\n🚩 Leadership exodus (CEO leaving for strategic investor)\n🚩 Customer concentration\n🚩 Unclear path to profitability\n\nNot all AI companies are created equal.",

            "6/ Our edge: We built a multi-agent system that:\n\n• Scans for opportunities daily\n• Scores against our thesis automatically\n• Refreshes research twice weekly\n\nAI investing, powered by AI. 🤖",

            "7/ The bottom line:\n\nThe window to invest in private AI companies before liquidity is narrowing.\n\n2026-2027 will see significant exit activity.\n\nPosition accordingly.\n\n/end\n\nFollow @EpochalCapital for more AI investment insights.",
        ]

    async def _draft_investor_update(self) -> dict:
        """Draft a quarterly investor update."""
        summary = self.portfolio.get_portfolio_summary()
        pipeline = self.portfolio.get_pipeline_summary()

        update = ContentDraft(
            content_type=ContentType.INVESTOR_UPDATE,
            title=f"Epochal Capital Investor Update - Q{(datetime.utcnow().month - 1) // 3 + 1} {datetime.utcnow().year}",
            body=self._generate_investor_update_body(summary, pipeline),
            target_audience="Limited Partners",
            tone=ContentTone.PROFESSIONAL,
        )

        return {
            "draft": update.to_dict(),
            "type": "Quarterly LP Update",
            "sections": [
                "Executive Summary",
                "Portfolio Performance",
                "Deal Pipeline",
                "Market Commentary",
                "Outlook",
            ],
        }

    def _generate_investor_update_body(self, summary, pipeline) -> str:
        """Generate investor update body."""
        return f"""
# Epochal Capital Investor Update
## Q{(datetime.utcnow().month - 1) // 3 + 1} {datetime.utcnow().year}

---

### Executive Summary

Dear Partners,

We are pleased to provide our quarterly update on Epochal Capital's activities and performance.

This quarter marked continued progress in our mission to identify and invest in private AI companies with upcoming liquidity events.

**Key Highlights:**
- Companies Tracked: {summary.companies_tracked}
- Active Deals in Pipeline: {summary.deals_in_pipeline}
- Active Positions: {summary.active_positions}

---

### Portfolio Performance

**Current Portfolio Metrics:**
- Total Invested: ${summary.total_invested_usd:,.0f}
- Current Value: ${summary.current_value_usd:,.0f}
- Unrealized Gain/Loss: ${summary.unrealized_gains_usd:,.0f}
- Total Return: {summary.total_return_pct:.1f}%

**Position Summary:**
- Active Positions: {summary.active_positions}
- Exited Positions: {summary.exited_positions}
- Realized Gains: ${summary.realized_gains_usd:,.0f}

---

### Deal Pipeline

Our sourcing efforts continue to identify attractive opportunities across the AI ecosystem.

**Pipeline by Status:**
{self._format_pipeline_status(pipeline)}

**Top Opportunities Under Review:**
We are currently evaluating several high-conviction opportunities that align with our thesis. Details available upon request.

---

### Market Commentary

The AI investment landscape continues to evolve rapidly:

**Macro Trends:**
- Enterprise AI adoption accelerating
- Foundation model competition intensifying
- Infrastructure demand outpacing supply
- Regulatory landscape taking shape

**IPO Market:**
- Several AI companies have hired IPO advisors
- Public market receptivity improving
- We expect increased activity in H1-H2 2026

---

### Outlook

We remain highly constructive on our thesis: private AI companies with upcoming liquidity events.

**Near-term Focus:**
1. Continue building pipeline of high-conviction opportunities
2. Deepen research on existing watchlist companies
3. Prepare for anticipated liquidity events

**Operational Updates:**
We continue to enhance our multi-agent research and monitoring systems, allowing us to track developments across our universe more efficiently.

---

### Contact

For questions or to schedule a call, please reach out to:
- Email: ir@epochal.capital
- Phone: [Contact Number]

Thank you for your continued partnership.

*The Epochal Capital Team*

---

*This update is confidential and intended solely for Epochal Capital limited partners.*
"""

    def _format_pipeline_status(self, pipeline: dict) -> str:
        """Format pipeline status for the update."""
        lines = []
        for status, data in pipeline.items():
            if data["count"] > 0:
                lines.append(f"- {status.replace('_', ' ').title()}: {data['count']} deals")
        return "\n".join(lines) if lines else "- No active deals in pipeline"

    async def _draft_fundraising_pitch(self) -> dict:
        """Draft fundraising pitch narrative."""
        pitch = ContentDraft(
            content_type=ContentType.PITCH_DECK_NARRATIVE,
            title="Epochal Capital - Investment Opportunity",
            body=self._generate_pitch_narrative(),
            target_audience="Prospective LPs, Family Offices, Institutional Investors",
            tone=ContentTone.PROFESSIONAL,
        )

        return {
            "draft": pitch.to_dict(),
            "type": "Fundraising Pitch Narrative",
            "recommended_sections": [
                "Firm Overview",
                "Investment Thesis",
                "Competitive Advantage",
                "Track Record",
                "Team",
                "Terms",
            ],
        }

    def _generate_pitch_narrative(self) -> str:
        """Generate fundraising pitch narrative."""
        return f"""
# Epochal Capital
## Investment Opportunity

---

### The Opportunity

Artificial Intelligence represents the most significant technological transformation since the internet. We are at an inflection point where:

1. **AI capabilities are accelerating** — Foundation models are achieving superhuman performance across an expanding range of tasks

2. **Enterprise adoption is mainstreaming** — AI is moving from experimentation to production across industries

3. **Liquidity events are approaching** — The best private AI companies are preparing for public markets

Epochal Capital is positioned to capture this opportunity through focused investment in **private AI companies with upcoming liquidity events**.

---

### Our Thesis

**Focus:** Private AI companies (Series B+) with clear paths to liquidity within 18-36 months

**Target Sectors:**
- Foundation Models (Anthropic, Mistral, Cohere)
- AI Infrastructure (Databricks, Cerebras, Lambda)
- AI Agents (Perplexity, Adept)
- Enterprise AI (Glean, Scale AI)
- Developer Tools (Hugging Face, Replit)

**Investment Criteria:**
- Valuation: $500M - $10B (preferred)
- Stage: Series B through Pre-IPO
- Revenue: $10M+ ARR with strong growth
- Liquidity Timeline: 18-36 months
- Discount to Last Round: 10%+ preferred

---

### Competitive Advantage

**1. AI-Native Operations**

We've built a multi-agent system that powers our investment process:
- Automated deal sourcing across 20+ companies
- Quantitative thesis scoring
- Twice-weekly research refresh
- Real-time liquidity signal monitoring

**2. Thesis Discipline**

Our scoring model ensures consistency:
- 25% weight on liquidity signals
- 25% weight on vertical fit
- 20% weight on investor quality
- 20% weight on stage fit
- 15% weight on revenue metrics

**3. Information Advantage**

Comprehensive coverage through:
- Multi-source intelligence gathering
- Leadership and M&A tracking
- Secondary market monitoring
- Network-based deal flow

---

### Investment Terms

**Fund Size:** [Target]
**Management Fee:** [X]%
**Carried Interest:** [X]%
**Minimum Investment:** [Amount]
**Fund Term:** [X] years

---

### Contact

To learn more about Epochal Capital:

Email: ir@epochal.capital
Web: www.epochal.capital

---

*This document is for informational purposes only and does not constitute an offer to sell or solicitation of an offer to buy any securities.*
"""

    async def _generate_market_commentary(self) -> dict:
        """Generate AI market commentary."""
        commentary = ContentDraft(
            content_type=ContentType.MARKET_COMMENTARY,
            title=f"AI Market Commentary - {datetime.utcnow().strftime('%B %Y')}",
            body=self._generate_commentary_body(),
            target_audience="Investors, Industry Professionals",
            tone=ContentTone.ANALYTICAL,
        )

        return {
            "draft": commentary.to_dict(),
            "type": "Market Commentary",
            "sections": [
                "Market Overview",
                "Sector Analysis",
                "Valuation Trends",
                "Outlook",
            ],
        }

    def _generate_commentary_body(self) -> str:
        """Generate market commentary body."""
        return f"""
# AI Market Commentary
## {datetime.utcnow().strftime('%B %Y')}

---

### Market Overview

The AI sector continues to demonstrate strong momentum as we enter {datetime.utcnow().year}. Key observations:

**Funding Environment:**
- Late-stage AI companies continue to attract capital
- Valuations have rationalized from 2021-2022 peaks
- Strategic investors (Microsoft, Google, NVIDIA) remain active

**IPO Pipeline:**
- Multiple companies have engaged IPO advisors
- Public market receptivity improving
- We expect significant activity in 2026

---

### Sector Analysis

**Foundation Models**
The race to build frontier AI systems continues to intensify. Key players (Anthropic, OpenAI, Mistral) are scaling rapidly with enterprise adoption accelerating.

*Outlook: Strong fundamentals, multiple IPO candidates*

**AI Infrastructure**
Compute and data infrastructure demand continues to outpace supply. GPU cloud providers (Lambda, CoreWeave) and chip companies (Cerebras, Groq) are scaling to meet demand.

*Outlook: Critical picks-and-shovels opportunity*

**Enterprise AI**
AI adoption in enterprise workflows is moving from experimentation to production. Vertical-specific solutions are gaining traction.

*Outlook: Clear revenue models, strong growth*

**AI Agents**
Autonomous AI systems represent the next frontier. Early but high-potential category with companies like Perplexity and Adept leading.

*Outlook: Early stage, significant long-term potential*

---

### Valuation Trends

- Late-stage AI companies trading at 15-30x ARR
- Pre-IPO companies commanding premium multiples
- Secondary market activity increasing
- Discount to last round availability varies by company

---

### Outlook

We remain constructive on the AI investment opportunity. Key themes to watch:

1. **IPO Activity** - Expect multiple high-profile offerings in 2026
2. **Consolidation** - Strategic M&A likely to accelerate
3. **Regulation** - AI governance frameworks taking shape
4. **Competition** - China/US dynamics evolving

*This commentary reflects the views of Epochal Capital and is for informational purposes only.*
"""
